"""Initial tables

Revision ID: 9700adbb10ec
Revises: 
Create Date: 2025-06-12 01:57:37.237680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9700adbb10ec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Post',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Title', sa.String(length=200), nullable=False),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('Price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ViewCount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Title')
    )
    op.create_table('User',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Email')
    )
    op.create_table('NotificationMembers',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=True),
    sa.Column('PostId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['PostId'], ['Post.Id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['UserId'], ['User.Id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('NotificationTrigger',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('NotificationId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['NotificationId'], ['NotificationMembers.Id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('NotificationTrigger')
    op.drop_table('NotificationMembers')
    op.drop_table('User')
    op.drop_table('Post')
    # ### end Alembic commands ###
